apiVersion: apps/v1
kind: Deployment
metadata:
  name: helath-probe
  labels:
    app: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
            - cat
            - /test-vol/liveness
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /test-vol/readiness
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - mountPath: /test-vol
          name: volume
      volumes:
      - name: volume
        hostPath:
          path: /data
          type: Directory  